### ISSUE TITLE
Default fonts 

### ISSUE THREAD

**Issue by dempseynoel** [olihawkins/pilot#2]
When applying the theme to a plot following warning received:

Warning message:
In grid.Call.graphics(C_text, as.graphicsAnnot(x$label), x$x, x$y,  :
  font family not found in Windows font database

I think this can be resolved by changing your defaults for each system (and when no system is detected) to the ggplot defaults of "sans" - this would apply Arial to the plots by default.

**Comment by olihawkins** [comment]
Thanks Noel. I am looking into this. If I can't find a way to get Trebuchet working as the defatult font on Windows I will set it to sans (which is the same as for Linux). I'll let you know here when it's fixed.
