### ISSUE TITLE
Feature request: Add tags for versions so that the package can be built using conda

### ISSUE THREAD

**Issue by davised** [olihawkins/pilot#4]
Hi there,

I have been liking the package thus far and I'm trying to use it in a reproducible data pipeline in conda.

While I can install the package after the conda env is set up, e.g. `Rscript -e 'remotes::install_github("olihawkins/pilot")'`, I have found it useful to generate a conda build recipe that I can reference locally for packages that aren't yet in a conda channel.

See here for more info: https://docs.conda.io/projects/conda-build/en/stable/user-guide/tutorials/build-r-pkgs.html

However, the `conda skeleton cran <github url>` depends on tags being present for the package.

I made a release and associated tag here https://github.com/davised/r-pilot and then added a release (choosing to add a tag (v4.0.1) and a target as that commit with the 4.0.1 prefix). Then, I was able to generate a skeleton in a conda env with the `conda-build` package installed: 
```bash
conda skeleton cran https://github.com/davised/r-pilot
conda-build --R 4.2.2 r-pilot
```
and I was able to install in the target env
```bash
mamba install -c file://path/to/conda-envs/envs/conda-build/conda-bld r-pilot
conda list | grep r-pilot
r-pilot                   4.0.1                     r42_0    file://path/to/conda-envs/envs/conda-build/conda-bld
```
I'm not sure how many people will use or benefit from this, and I can certainly maintain my own fork that has tags, but I think this is a low-effort enhancement. 

Additionally, I don't know exactly how the packages end up in say, the conda-forge channel, but having tags would allow your package to make it in there at some point.

Thanks for providing the package.

Cheers,

Ed

**Comment by olihawkins** [comment]
Hi Ed. No worries, I should have done this before. I've pushed a tag and created a release for 4.0.1. Let me know if this now works in your pipeline.
